urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('register', views.register, name='register'),
    path('confirm_logout', views.logout, name='confirm_logout'),
    path('search', views.search, name='search'),
    # buddies
    path('buddies/category/', views.buddies, name='buddies'),
    path('buddies/category', views.buddies, name='buddies'),
    path('buddies/', views.buddies, name='buddies'),
    path('buddies', views.buddies, name='buddies'),
    path('buddies/<int:id>/alone', views.buddy_details_alone, name='buddy_details_alone'),
    path('buddies/<int:id>', views.buddy_details, name='buddy_details'),
    path('buddies/category/<int:cat>', views.buddies, name='buddies_cat'),
    # locations
    path('locations/category/', views.locations, name='locations'),
    path('locations/category', views.locations, name='locations'),
    path('locations/', views.locations, name='locations'),
    path('locations', views.locations, name='locations'),
    path('locations/<int:id>', views.location_details, name='location_details'),
    path('locations/map/', views.locations_map, name='locations_map'),
    path('locations/heatmap/', views.locations_heatmap, name='locations_heatmap'),
    path('locations/category/<int:cat>', views.locations, name='locations_cat'),
    # meetups with cal
    path('meetups_cal/', views.meetups_cal, name='meetups_cal'),
    path('meetups_cal', views.meetups_cal, name='meetups_cal'),
    # meetups
    path('meetups/', views.meetups, name='meetups'),
    path('meetups', views.meetups, name='meetups'),
    path('meetups/<int:id>', views.meetup_details, name='meetup_details'),
    path('meetups/category/0-<int:cat>', views.meetups2, name='meetups_cat2'),
    path('meetups/category/<int:cat>-0', views.meetups3, name='meetups_cat3'),
    path('meetups/category/<str:cat>', views.meetups, name='meetups_cat'),
    # categories
    path('categories/', views.categories, name='categories'),
    path('categories', views.categories, name='categories'),
    path('categories/<int:id>', views.category_details, name='category_details'),
    # admin stuff
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
]

models.py
from django.db import models
from django.db.models import Min
from django.db.models import Max
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from datetime import date

class User(AbstractUser):
  pass

class Category(models.Model):
  class CategoryType(models.IntegerChoices):
    BUDDY = 1
    LOCATION = 2
  # Fields
  name = models.CharField(max_length=50)
  owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  category_type = models.IntegerField(choices=CategoryType, default=1)
  #counter = models.PositiveIntegerField(default=0)

  # Metadata
  class Meta:
    ordering = ['-name']
    unique_together = ('owner', 'name')

  # Methods
  def get_absolute_url(self):
    """Returns the URL to access a particular instance of MyModelName."""
    return reverse('model-detail-view', args=[str(self.id)])

  def __str__(self):
    """String for representing the object (in Admin site etc.)."""
    return self.name

  @property
  def how_often_location(self):
    return Location.objects.filter(category__exact=self.id).count()

  @property
  def how_often_buddy(self):
    return Buddy.objects.filter(category__exact=self.id).count()


class Location(models.Model):
  # Fields
  name = models.CharField(max_length=50)
  owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  lng = models.FloatField(blank=True, null=True)
  lat = models.FloatField(blank=True, null=True)
  category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True, blank=True)

  # Metadata
  class Meta:
    ordering = ['-name']
    unique_together = ('owner', 'name')

  # Methods
  def get_absolute_url(self):
    """Returns the URL to access a particular instance of MyModelName."""
    return reverse('model-detail-view', args=[str(self.id)])

  def __str__(self):
    """String for representing the object (in Admin site etc.)."""
    return self.name

  @property
  def how_often(self):
    return Meetup.objects.filter(location__exact=self.id).count()

  @property
  def meetups(self):
    return Meetup.objects.filter(location__exact=self.id).order_by('-date')

  @property
  def date_diff(self):
    min = Meetup.objects.filter(location__exact=self.id).aggregate(Min('date'))
    max = Meetup.objects.filter(location__exact=self.id).aggregate(Max('date'))
    return (max['date__max'] - min['date__min']).days + 1

  @property
  def frequency(self):
    how_often = self.how_often
    if how_often > 0:
      return self.date_diff / how_often
    return 0

  @property
  def latest_meetup(self):
    return Meetup.objects.filter(location__exact=self.id).order_by('-date')[0]


class Buddy(models.Model):
  # Fields
  name = models.CharField(max_length=50)
  owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True, blank=True)

  # Metadata
  class Meta:
    ordering = ['name']
    unique_together = ('owner', 'name')

  # Methods
  def get_absolute_url(self):
    """Returns the URL to access a particular instance of MyModelName."""
    return reverse('model-detail-view', args=[str(self.id)])

  def __str__(self):
    """String for representing the object (in Admin site etc.)."""
    return self.name

  @property
  def how_often(self):
    return Meetup.objects.filter(buddies__id__exact=self.id).count()

  @property
  def meetups(self):
    return Meetup.objects.filter(buddies__id__exact=self.id).order_by('-date')

  @property
  def date_diff(self):
    min = Meetup.objects.filter(buddies__id__exact=self.id).aggregate(Min('date'))
    max = Meetup.objects.filter(buddies__id__exact=self.id).aggregate(Max('date'))
    return (max['date__max'] - min['date__min']).days + 1

  @property
  def frequency(self):
    how_often = self.how_often
    if how_often > 0:
      return self.date_diff / how_often
    return 0

  @property
  def latest_meetup(self):
    return Meetup.objects.filter(buddies__id__exact=self.id).order_by('-date')[0]


class Meetup(models.Model):
  # Fields
  name = models.CharField(max_length=50)
  owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  location = models.ForeignKey(Location, on_delete=models.PROTECT)
  buddies = models.ManyToManyField(Buddy)
  date  = models.DateField(default=date.today)

  # check date validity during save
  def save(self, *args, **kwargs):
    if self.date > date.today():
      raise ValidationError("The date cannot be in the future!")
    super(Meetup, self).save(*args, **kwargs)


  # Metadata
  class Meta:
    ordering = ['-name']
    unique_together = ('owner', 'name', 'date', 'location')

  # Methods
  def get_absolute_url(self):
    """Returns the URL to access a particular instance of MyModelName."""
    return reverse('model-detail-view', args=[str(self.id)])

  def __str__(self):
    """String for representing the object (in Admin site etc.)."""
    return self.name
    
  @property
  def buddies_list(self):
    return ", ".join([i.name for i in self.buddies.all()])


class Logger(models.Model):
  page = models.CharField(max_length=250)
  referrer = models.CharField(max_length=250, blank=True, null=True)
  method = models.CharField(max_length=50, blank=True, null=True)
  timestamp = models.DateTimeField(auto_now_add=True)

  # Metadata
  class Meta:
    ordering = ['-timestamp']

  def __str__(self):
    """String for representing the object (in Admin site etc.)."""
    return self.page + " <- " + str(self.referrer)
    

templates/about_snippet.html
<p>Just a hobby project to track meeting my buddies.</p>
Ideas for improvement:
<ul>
<li>Buddy<ul>
<li>add contact information</li>
<li>...</li>
</ul></li>
<li>Location<ul>
<li>...</li>
</ul></li>
<li>Meetup<ul>
<li>New meetup on start screen? With "plaintext" input?</li>
<li>show calendar on start screen with meetups? maybe like github contribution matrix</li>
<li>optional comment field for meetup</li>
<li>Add all meetups underneath location map-popup</li>
<li>Sort buddies alphabetically</li>
<li>...</l>
</ul></li>
<li>User<ul>
<li>pw reset</li>
<li>settings, e.g., map position & zoom</li>
<li>...</li>
</ul></li>
<li>...</li>
</ul>

<p>
<a href="https://www.djangoproject.com/" target="_blank">Built with Django<br>
<img src="/static/django2.png" width="200"/></a>
<br>
<a href="https://simplecss.org/" target="_blank">Using Simple CSS</a>
</p>
<p>
<a href="https://uberspace.de/" target="_blank">Hosted on uberspace<br>
<img src="/static/uberspace.png" width="200"/></a>
</p>
<p>
<a href="https://github.com/paulberlin/treffen/" target="_blank">Source on github<br>
<img src="/static/github.png" width="200"/></a>
</p>

templates/base.html
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/simple.min.css">
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico">
    <title>Buddy-Logger{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
    <link rel="stylesheet" href="/static/custom.css">
</head>
<body>
  <header>
    <a href="/"><img src="/static/buddy_logger_2.png" alt="Logo"/></a>
{% if user.is_authenticated %}
<nav>
  <a href="{% url 'buddies' %}" {% if highlight == 'buddies' %}class="current"{% endif %}>👥 My Buddies</a>
  <a href="{% url 'locations' %}" {% if highlight == 'locations' %}class="current"{% endif %}>📍 My Locations</a>
  <a href="{% url 'meetups' %}" {% if highlight == 'meetups' %}class="current"{% endif %}>🗓️ My Meetups</a>
  <a href="{% url 'categories' %}" {% if highlight == 'categories' %}class="current"{% endif %}>🏷️ My Categories</a>
  <a id="logout_link" style="background:var(--accent);color:var(--bg);" href="{% url 'confirm_logout' %}" onclick="document.getElementById('logout').submit()">Logout</a>
  <script>document.getElementById("logout_link").href="#";</script>
</nav>
<form action="{% url 'logout' %}" method="post" id="logout">
  {% csrf_token %}
</form>
<form method="get" action="/search">
<input type="text" name="q" value="{{ searchtext }}">
<button type="submit">Search</button>
</form>
{% else %}
<nav>
<a style="background:var(--accent);color:var(--bg); padding: .1rem 1rem !important;" href="{% url 'login' %}">Login</a>
</nav>
{% endif %}
</header>

<main>
{% if user.is_authenticated %}

{% block content %}Welcome to Buddy-Logger.{% endblock %}

{% else %}

{% block login %}
Hi, welcome to Buddy Logger!

<p>Please <a href="{% url 'login' %}">login</a> to get started or <a href="{% url 'register' %}">register</a>.</p>
{% endblock %}

{% endif %}

<script>
var url = document.location.href;
if (url.match(/#new$/)) {
  document.getElementById('new').open = true
}
</script>
</main>

<footer>
<p><a href="{% url 'about' %}">About</a> | &copy; Paul Führing</p>
</footer>
</body>
</html>

templates/buddies.html
{% extends "base.html" %}

{% block title %} - Buddies{% endblock %}

{% block content %}
Hi {{ user.username }}, 
here's a list of your buddies:
<br>You can also <a href="#new" onclick="document.getElementById('new').open = true;">add a new buddy</a>.
<p>
 
{% if buddies_without_category %}
<details>
<summary><em>No category</em></summary>
<ul>
  {% for buddy in buddies_without_category %}
    <li>{% include "buddy_snippet.html" with buddy=buddy %}</li>
  {% endfor %}
</ul>
</details>
{% endif %}


{% for cat in categories %}
{% if cat.how_often_buddy > 0 %}
<details
{% if filter %}
open
{% endif %}
>
<summary>{{ cat }} ({{ cat.how_often_buddy }})</summary>
<ul>
  {% for buddy in cat.buddy_set.all|dictsort:"name" %}
    <li>{% include "buddy_snippet.html" with buddy=buddy %}</li>
  {% endfor %}
</ul>
{% if filter %}
<a href="{% url 'buddies' %}">Clear filter</a>
{% else %}
<a href="{% url 'meetups_cat3' cat.id %}">See meetups of this category</a>
{% endif %}
</details>
{% endif %}
{% endfor %}

<details {{ open_details }} id="new">
<summary>Add a buddy</summary>
<form action="" method="post">
{{ form }}
{% csrf_token %}
<input type="submit" value="Make it so!">
</form>
</details>
</p>

{% endblock %}

templates/buddy.html
{% extends "base.html" %}

{% block title %} - Buddy {{ buddy.name }}{% endblock %}

{% block head %}
<link rel="stylesheet" href="/static/leaflet/dist/leaflet.css" />
<script src="/static/leaflet/dist/leaflet.js"></script>
{% endblock %}

{% block content %}
Hi {{ user.username }}, 
here are the details of your buddy <em>{{ buddy.name }}</em>{% if buddy.category %} (category: {{ buddy.category }}){% endif %}:
<br>
{% if alone %}
<a href="{% url 'buddy_details' buddy.id %}">Show all meetups with this buddy.</a>
{% else %}
<a href="{% url 'buddy_details_alone' buddy.id %}">Show meetups with this buddy alone.</a>
{% endif %}

{% if how_often > 2 %}
<aside><p>
On average, you met with this buddy every
{{ frequency | floatformat:-1 }}
days.
{% if last_meetup_days > buddy.frequency %}
Your last meetup is already {{ last_meetup_days }} days ago, time to meet again?!
{% endif %}
</p></aside>
{% endif %}

{% if how_often > 2 %}
{% include "meetups_cal.html" with meetups=meetups %}
{% endif %}

{% if how_often > 0 %}
{% include "meetups_snippet.html" with meetups=meetups %}
{% endif %}


<details>
<summary>Add a new meetup with this buddy</summary>
{% if locations_amount == 0 %}
Please <a href="{%url 'locations' %}#new">add a location</a> first.
{% else %}
<form action="{% url 'meetups' %}" method="post">
{{ newmeetup_form }}
{% csrf_token %}
<input type="submit" value="Make it so!">
</form>
{% endif %}
</details>

<details {{ open_details }}>
<summary>Update buddy</summary>
<p>
<form action="" method="post" id="form">
{{ form }}
{% csrf_token %}
<input type="submit" value="Make it so!">
<br>
<a href="#" onclick="document.getElementById('delete_prompt').showModal()">Delete buddy</a>
<dialog id="delete_prompt">
<p>Please confirm deleting buddy <em>{{ buddy.name }}</em><br>
(Note that the buddy will be removed from meetups, but the meetup itself remains.)</p>
<button onclick="document.getElementById('id_delete').value='1';document.getElementById('form').submit()">Confirm</button>
<br>
<a href="#" onclick="document.getElementById('delete_prompt').close()">Never mind</a>
</dialog>

</form>
</p>
</details>
<p><a href="{% url 'buddies' %}">Back to buddies list</a></p>

{% endblock %}

templates/buddy_snippet.html
<a href="{% url 'buddy_details' buddy.id %}">{{ buddy.name }}</a> 
{% if buddy.how_often > 0 %}
(met
{% if buddy.how_often == 1 %}one time, on
{% else %}{{ buddy.how_often }} times, latest on{% endif %}
{{ buddy.latest_meetup.date|date:"Y-m-d" }})
{% else %}
(not met yet)
{% endif %}

templates/categories.html
{% extends "base.html" %}

{% block title %} - Categories{% endblock %}

{% block content %}
Hi {{ user.username }}, 
here's a list of your categories:
<br>You can also <a href="#new" onclick="document.getElementById('new').open = true;">add a new category</a>.
<p>

<details>
<summary>Buddy Categories</summary>
<ul>
     {% for category in buddy_categories %}
        <li><a href="{% url 'category_details' category.id %}">{{ category.name }}</a> ({{category.how_often_buddy}})</li>
     {% empty %} 
        <li>None yet :-/</li>
     {% endfor %}
</ul>
</details>

<details>
<summary>Location Categories</summary>
<ul>
     {% for category in location_categories %}
        <li><a href="{% url 'category_details' category.id %}">{{ category.name }}</a> ({{category.how_often_location}})</li>
     {% empty %} 
        <li>None yet :-/</li>
     {% endfor %}
</ul>
</details>

<details {{ open_details }} id="new">
<summary>Add a category</summary>
<form action="" method="post">
{{ form }}
{% csrf_token %}
<input type="submit" value="Make it so!">
</form>
</details>

</p>
{% endblock %}

templates/category.html
{% extends "base.html" %}

{% block title %} - Category {{ category.name }}{% endblock %}

{% block content %}
Hi {{ user.username }}, 
here are the details of your category <em>{{ category.name }}</em>:

<ul>
{% if category.category_type == 1 %}
<li>Used at 
{% if category.how_often_buddy == 0 %}no buddies yet
{% else %}
<a href="{% url 'buddies_cat' category.id %}">{% if category.how_often_buddy == 1 %}one buddy</a> 
{% else %}{{ category.how_often_buddy }} buddies</a>{% endif %}
{% endif %}
</li>
{% else %}
<li>Used at 
{% if category.how_often_location == 0 %}no locations yet
{% else %}
<a href="{% url 'locations_cat' category.id %}">{% if category.how_often_meetup == 1 %}one location</a> 
{% else %}{{ category.how_often_location }} locations</a>{% endif %}
{% endif %}
</li>
{% endif %}
</ul>

<details {{ open_details }}>
<summary>Update category</summary>
<p>
<form action="" method="post" id="form">
{{ form }}
{% csrf_token %}
<input type="submit" value="Make it so!">
<br>
<a href="#" onclick="document.getElementById('delete_prompt').showModal()">Delete category</a>
<dialog id="delete_prompt">
<p>Please confirm deleting category <em>{{ category.name }}</em><br>
(Note that the category can only be removed when it's not used at any location or buddy.)</p>
<button onclick="document.getElementById('id_delete').value='1';document.getElementById('form').submit()">Confirm</button>
<br>
<a href="#" onclick="document.getElementById('delete_prompt').close()">Never mind</a>
</dialog>
</form>
</p>
</details>
<p><a href="{% url 'categories' %}">Back to categories list</a></p>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %} - Welcome{% endblock %}

{% block content %}
Hi {{ user.username }}, welcome to Buddy Logger!


{% if categories_count == 0 %}
<p>No Categories were created yet, in order to create one, please <a href="{% url 'categories' %}#new">click here.</a>
You can optionally assign a Category to a Location or Buddy, that allows for filtering and makes it easier to keep an overview.
</p>
{% endif %}

{% if buddies_count == 0 %}
<p>There is no Buddy yet, you can go ahead with <a href="{% url 'buddies' %}#new">creating a buddy.</a>
Each meetup you create contains at least one buddy.
</p>
{% endif %}

{% if locations_count == 0 %}
<p>You didn't create a Location yet, you can <a href="{% url 'locations' %}#new">do so here.</a>
A meetup takes place at a certain location.
</p>
{% endif %}

{% if locations_count > 0 and buddies_count > 0 and not meetup %}
<p>You can <a href="{% url 'meetups' %}#new">create a Meetup</a> now. A Meetup comprises of Buddies and a Location.</p>
{% endif %}

<p>
{% if frequency > 1 %}
On average, you have a meetup every
{{ frequency | floatformat:-1 }}
days.
{% endif %}
{% if days_since_last_meetup > frequency %}
Your last meetup is already {{ days_since_last_meetup }} days ago, time to organize a meetup again?!
{% endif %}
</p>


{% if meetup %}
<p>Last meetup was <a href="{% url 'meetup_details' meetup.id %}">{{ meetup.name }} (@{{ meetup.location }}, 
    with {{ meetup.buddies_list }})</a> on {{ meetup.date|date:"Y-m-d" }}</p>
{% endif %}

{% if location.how_often > 1 %}
<p>Location visited the most is 
<a href="{% url 'location_details' location.id %}">{{ location.name }}</a>
(visited {{ location.how_often }} times, latest on
{{ location.latest_meetup.date|date:"Y-m-d" }})</p>
{% endif %}

{% if buddy.how_often > 1 %}
<p>Buddy met the most is
{% include "buddy_snippet.html" with buddy=buddy %}
</p>
{% endif %}

{% if category %}
<p>Most busy category is <a href="{% url 'category_details' category.id %}">{{ category }}</a></p>
{% endif %}

{% endblock %}

templates/location.html
{% extends "base.html" %}

{% block title %} - Location {{ location.name }}{% endblock %}

{% block head %}
<link rel="stylesheet" href="/static/leaflet/dist/leaflet.css"/>
<script src="/static/leaflet/dist/leaflet.js"></script>
<link rel="stylesheet" href="/static/leaflet/Control.Geocoder.css"/>
<script src="/static/leaflet/Control.Geocoder.js"></script>
{% endblock %}

{% block content %}
Hi {{ user.username }}, 
here are the details of your location <em>{{ location.name }}</em>{% if location.category %} (category: {{ location.category }}){% endif %}:

{% if location.how_often > 2 %}
<aside><p>
On average, you visit this place every 
{{ location.frequency | floatformat:-1 }}
days.
</aside></p>
{% endif %}

{% if location.how_often > 2 %}
{% include 'meetups_cal.html' with meetups=location.meetups %}
{% endif %}

{% include 'meetups_snippet.html' with meetups=location.meetups nomap=1 %}

<details>
<summary>Add a new meetup for this location</summary>
{% if buddies_amount == 0 %}
Please <a href="{% url 'buddies' %}#new">add a buddy</a> first.
{% else %}
<form action="/meetups" method="post">
{{ newmeetup_form }}
{% csrf_token %}
<input type="submit" value="Make it so!">
</form>
{% endif %}
</details>

<details {{ open_details }}>
<summary>Update location</summary>
<p>
<a name="update"></a>
<form action="" method="post" id="form">
{{ form }}
{% csrf_token %}
<a href="#update" onclick="removeMarker()">Clear marker</a>
<div style="height: 180px;" id="update_map"></div>
<input type="submit" value="Make it so!">
<br>
<a href="#update" onclick="document.getElementById('delete_prompt').showModal()">Delete location</a>
<dialog id="delete_prompt">
<p>Please confirm deleting location <em>{{ location.name }}</em><br>
(Note that the location can only be removed when it's not used at any meetup.)</p>
<button {% if location.how_often == 0 %} onclick="document.getElementById('id_delete').value='1';document.getElementById('form').submit()" {% else %} disabled="true" {% endif %}>Confirm</button>
<br>
<a href="#update" onclick="document.getElementById('delete_prompt').close()">Never mind</a>
</dialog>

</form>
</p>
</details>
<p><a href="{% url 'locations' %}">Back to locations list</a></p>

<script>
var update_map = L.map('update_map').setView([{{ map_lat }}, {{ map_lng }}], 13);
L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
}).addTo(update_map);
L.Control.geocoder({
  defaultMarkGeocode: false
}).on('markgeocode', function(e) {
    var bbox = e.geocode.bbox;
    var poly = L.polygon([
      bbox.getSouthEast(),
      bbox.getNorthEast(),
      bbox.getNorthWest(),
      bbox.getSouthWest()
    ]).addTo(update_map);
    update_map.fitBounds(poly.getBounds());
  }).addTo(update_map);
var marker;
{% if location.lng %}
marker = L.marker([{{ location.lat }}, {{ location.lng }}]).addTo(update_map);
{% endif %}
function onMapClick(e) {
    //alert("You clicked the map at " + e.latlng);
    if (marker) {
        marker.setLatLng(e.latlng);
    } else {
	marker = L.marker(e.latlng).addTo(update_map);
    }
    document.getElementById('id_lng').value = e.latlng.lng;
    document.getElementById('id_lat').value = e.latlng.lat;
}
function removeMarker() {
    update_map.removeLayer(marker);
    marker = null;
    document.getElementById('id_lng').value = "";
    document.getElementById('id_lat').value = "";
}
update_map.on('click', onMapClick);
</script>

{% endblock %}

templates/location_snippet.html
<a href="{% url 'location_details' location.id %}">{{ location.name }}</a>
{% if location.how_often > 0 %}(visited
{% if location.how_often == 1 %}one time, on
{% else %}{{ location.how_often }} times, latest on{% endif %}
{{ location.latest_meetup.date|date:"Y-m-d" }})
{% else %}(not visited yet){% endif %}

templates/meetup.html
{% extends "base.html" %}

{% block title %} - Meetup{% endblock %}

{% block content %}
Hi {{ user.username }}, 
here are the details of your meetup <em>{{ meetup.name }}</em>:

<div class="timeline">
<div class="timeline-line" role="presentation">
</div>
<ol class="timeline-events">
        <li class="timeline-event">
        <div class="timeline-date"><time>{{ meetup.date|date:"Y-m-d" }}</time></div>
        <div class="timeline-description">
{{ meetup.name }} (<a href="{% url 'location_details' meetup.location.id %}">@{{ meetup.location }}</a>, 
        with 
{% for buddy in meetup.buddies.all %}
<a href="{% url 'buddy_details' buddy.id %}">{{ buddy.name }}</a>{% if not forloop.last %},{% endif %}{% endfor %})
        </div>
        </li>
</ol><!-- /.timeline-events -->
</div><!-- /.timeline -->
</div><!-- /.container -->


<details {{ open_details }}>
<summary>Update meetup</summary>
<p>
<form action="" method="post" id="form">
{{ form }}
{% csrf_token %}
<input type="submit" value="Make it so!">
<br>
<a href="#" onclick="document.getElementById('delete_prompt').showModal()">Delete meetup</a>
<dialog id="delete_prompt">
<p>Please confirm deleting meetup <em>{{ meetup.name }}</em><br>
(Note that the meetup will be removed, but the buddies and location remain.)</p>
<button onclick="document.getElementById('id_delete').value='1';document.getElementById('form').submit()">Confirm</button>
<br>
<a href="#" onclick="document.getElementById('delete_prompt').close()">Never mind</a>
</dialog>

</form>
</p>
</details>
<p><a href="{% url 'meetups' %}">Back to meetups list</a></p>

{% endblock %}

templates/meetups_cal.html
{% if meetups %}

<script type="importmap">
{
"imports": {
"lit": "https://esm.sh/lit@3.2.0",
"lit/": "https://esm.sh/lit@3.2.0/"
}
}
</script>
<script type="module" src="/static/activity-graph.min.js"></script>

<style>
activity-graph {
--activity-graph-text-color: var(--text);
}
figcaption {
padding-top: 1rem;
}
</style>

<activity-graph 
	class=".activity-graph-dark"
	range-start="{{ first_meetup|date:"Y-m-d" }}"
	range-end="{{ last_meetup|date:"Y-m-d" }}"
	activity-data="{% for meetup in meetups %}{{ meetup.date|date:"Y-m-d" }}{% if not forloop.last %},{%endif %}{% endfor %}"
	activity-levels="0,1,2,3"
	first-day-of-week="1"
	lang="de"
></activity-graph>


{% endif %}